export interface Beat {
  id: string;
  title: string;
  artist: string;
  bpm: number;
  key: string;
  price: number;
  cover: string;
  tags: string[];
  releaseDate: string;
  youtubeUrl?: string; // YouTube video URL
  audioUrl?: string; // Placeholder for now
  memberOnly: boolean; // New property for member-only beats
}

export const beats: Beat[] = [
  {
    id: "1",
    title: "THUNDERSHOCK",
    artist: "3LIXIR Exclusive",
    bpm: 120,
    key: "Em",
    price: 749.99,
    cover: "/Megamix-Cover.png",
    tags: ["EDM", "House", "Atmospheric"],
    releaseDate: "2026-01-02",
    youtubeUrl: "https://youtu.be/RamMgoQDEso",
    memberOnly: false,
  },
  {
    id: "2",
    title: "EVOLUTION",
    artist: "3LIXIR Exclusive",
    bpm: 100,
    key: "D",
    price: 299.99,
    cover: "/Megamix-Cover.png",
    tags: ["Etheral", "Boom Bap", "LOFI"],
    releaseDate: "2026-01-02",
    youtubeUrl: "https://youtu.be/czWOFYrTASo",
    memberOnly: false,
  },
  {
    id: "3",
    title: "CHRONOPHOBIA",
    artist: "3LIXIR Exclusive",
    bpm: 120,
    key: "F",
    price: 149.99,
    cover: "/Megamix-Cover.png",
    tags: ["Synthwave", "LOFI", "EDM"],
    releaseDate: "2026-01-02",
    youtubeUrl: "https://youtu.be/URACea9_w2Q",
    memberOnly: true,
  },
  {
    id: "4",
    title: "KINGCRAFT",
    artist: "3LIXIR Exclusive",
    bpm: 100,
    key: "D#",
    price: 649.99,
    cover: "/Megamix-Cover.png",
    tags: ["Boom Bap", "EDM", "LOFI"],
    releaseDate: "2026-01-03",
    youtubeUrl: "https://youtu.be/9HMeD5Hy_FU",
    memberOnly: false,
  },
  {
    id: "5",
    title: "THE HORYZON",
    artist: "3LIXIR Exclusive",
    bpm: 85,
    key: "Dm",
    price: 449.99,
    cover: "/Megamix-Cover.png",
    tags: ["EDM", "LOFI", "Trap"],
    releaseDate: "2026-01-03",
    youtubeUrl: "https://youtu.be/1FewK3a-3l4",
    memberOnly: false,
  },
  {
    id: "6",
    title: "THE CROP BUMPER",
    artist: "3LIXIR Exclusive",
    bpm: 110,
    key: "Db",
    price: 249.99,
    cover: "/Megamix-Cover.png",
    tags: ["LOFI", "Jazz", "Boombap"],
    releaseDate: "2026-01-03",
    youtubeUrl: "https://youtu.be/7WRtUYAtOqk",
    memberOnly: false,
  },
  {
    id: "7",
    title: "SUBURBIA",
    artist: "3LIXIR Exclusive",
    bpm: 120,
    key: "E",
    price: 1949.99,
    cover: "/Megamix-Cover.png",
    tags: ["EDM", "House", "cinematic"],
    releaseDate: "2026-01-12",
    youtubeUrl: "https://youtu.be/fBU5HTRvtPc",
    memberOnly: false,
  },
  {
    id: "8",
    title: "ARCADE",
    artist: "3LIXIR Exclusive",
    bpm: 100,
    key: "D#m",
    price: 249.99,
    cover: "/Megamix-Cover.png",
    tags: ["LOFI", "Liminal", "EDM"],
    releaseDate: "2026-01-12",
    youtubeUrl: "https://youtu.be/q1BUr1nkRAo",
    memberOnly: false,
  },
  {
    id: "9",
    title: "SPACE CADET",
    artist: "3LIXIR Exclusive",
    bpm: 120,
    key: "Em",
    price: 149.99,
    cover: "/Megamix-Cover.png",
    tags: ["House", "EDM", "Club"],
    releaseDate: "2026-01-12",
    youtubeUrl: "https://youtu.be/nNExA6NHn5s",
    memberOnly: true,
  },
  {
    id: "10",
    title: "INCIDIOUS",
    artist: "3LIXIR Exclusive",
    bpm: 210,
    key: "Em",
    price: 1449.99,
    cover: "/Megamix-Cover.png",
    tags: ["Dubstep", "EDM", "Boom Bap"],
    releaseDate: "2026-01-12",
    youtubeUrl: "https://youtu.be/SNy6AtR55yM",
    memberOnly: true,
  },
  {
    id: "11",
    title: "VIBIN'",
    artist: "3LIXIR Exclusive",
    bpm: 120,
    key: "F#",
    price: 1249.99,
    cover: "/Megamix-Cover.png",
    tags: ["EDM", "Techno", "House"],
    releaseDate: "2026-01-12",
    youtubeUrl: "https://youtu.be/9C9JfqOdQNQ",
    memberOnly: false,
  },
  {
    id: "12",
    title: "SHIMMERING",
    artist: "3LIXIR Exclusive",
    bpm: 150,
    key: "Db",
    price: 1949.99,
    cover: "/Megamix-Cover.png",
    tags: ["EDM", "Dubstep", "Techno"],
    releaseDate: "2026-01-12",
    youtubeUrl: "https://youtu.be/9C9JfqOdQNQ",
    memberOnly: false,
  },
  {
    id: "13",
    title: "ATHERIAL WAVES",
    artist: "3LIXIR Exclusive",
    bpm: 175,
    key: "C",
    price: 549.99,
    cover: "/Aetherial Waves.png",
    tags: ["Boom Bap"],
    releaseDate: "2026-07-23",
    youtubeUrl: "https://youtu.be/maZyN5z-u3E",
    memberOnly: false,
  },
  {
    id: "14",
    title: "LAZERBEAM",
    artist: "3LIXIR Exclusive",
    bpm: 150,
    key: "Am",
    price: 349.99,
    cover: "/Lazerbeam.png",
    tags: ["Trap"],
    releaseDate: "2026-07-23",
    youtubeUrl: "https://youtu.be/BSd0HVoYj50",
    memberOnly: false,
  },
  {
    id: "15",
    title: "No Pressure",
    artist: "3LIXIR Exclusive",
    bpm: 110,
    key: "B",
    price: 249.99,
    cover: "/NO PRESSURE.png",
    tags: ["Boom Bap"],
    releaseDate: "2026-07-23",
    youtubeUrl: "https://youtu.be/O4emOo_1mX8",
    memberOnly: false,
  },
];
